apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.name }}-admin-sa
  namespace: {{ .Values.env.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.admin.iam_role_arn }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.env.name }}-sa-role
  namespace: {{ .Values.env.compute_namespace }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.env.name }}-sa-role-binding
  namespace: {{ .Values.env.compute_namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.env.name }}-admin-sa
    namespace: {{ .Values.env.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.env.name }}-sa-role
