apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.name }}-secrets
  namespace: {{ .Values.env.namespace }}
type: Opaque
stringData:
  kc-client-secret: "{{ .Values.admin.kc_client_secret }}"