apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Values.env.name}}-proxy
  namespace: {{.Values.env.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.env.name}}-proxy
  policyTypes:
    - Ingress
  ingress:
  - {}     # allow from anywhere