apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.env.name }}"
  name: {{ .Values.env.service }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: "{{ .Values.env.name }}"
  sessionAffinity: None
  type: ClusterIP