apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Values.env.name}}-admin
  namespace: {{.Values.env.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.env.name}}-admin
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{.Values.env.compute_namespace}}
        # (optional, but nice to be explicit)
      ports:
        - port: 8000
          protocol: TCP