apiVersion: v1
kind: Service
metadata:
  name: {{.Values.env.name}}-admin
  namespace: {{.Values.env.namespace}}
spec:
  selector:
    app: {{.Values.env.name}}-admin
  ports:
  - name: admin
    port: 8000
    targetPort: 8000
  type: ClusterIP