apiVersion: v1
kind: Service
metadata:
  name: {{.Values.env.name}}-proxy
  namespace: {{.Values.env.namespace}}
spec:
  selector:
    app: {{.Values.env.name}}-proxy
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: rest
    port: 8080
    targetPort: 8080
  type: ClusterIP