apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Values.env.name}}
  namespace: {{.Values.env.namespace}}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.env.name}}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{.Values.env.name}}-proxy
    ports:
    - protocol: TCP
      port: 8000   # Triton rest port
    - protocol: TCP
      port: 8001   # Triton gRPC port
    - protocol: TCP
      port: 8002   # Triton metrics port
