image:
  repository: quay.io/domino
  container: domino-extensions-api
  appVersion: v1.0.0
  pullPolicy: Always

env:
  name: domino-extensions-api
  service: domino-extensions-api-svc
  namespace:
    platform: domino-platform
    compute: domino-compute
istio:
  enabled: false

